### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by mistek131995** [Wanwire/FloxcoreTun2SocksKit#1]
<img width="1470" alt="Снимок экрана 2024-06-22 в 18 42 49" src="https://github.com/Wanwire/FloxcoreTun2SocksKit/assets/14914380/602ce03c-cdf6-44bd-a832-1f223f64c0ee">
<img width="1470" alt="Снимок экрана 2024-06-22 в 18 42 59" src="https://github.com/Wanwire/FloxcoreTun2SocksKit/assets/14914380/de98b470-9300-4de2-9de8-d8526d0e08a5">

**Comment by tveerman** [comment]
Are you calling Socks5Tunnel.run from a Network (App) Extension? Normal apps run in an sandboxed environment and cannot access NEPacketTunnelFlow API that's used by HevSocks5Tunnel. If you are running it from a Network Extension, then please verify that you've enabled the Packet Tunnel Network Extensions capabilities (select your network extension target, go to Signing & Capabilities tab, scroll down to Network Extensions).
